all:
	pdflatex bachelor.tex
	bibtex bachelor.aux
	pdflatex bachelor.tex
	pdflatex bachelor.tex

clean:
	rm *~ &
	rm *.aux &
	rm *.log &
	rm *.bbl &
	rm *.blg &
	rm *.toc &
	rm *.lof &
	rm *.lot &
	rm *.idx &
	rm *.backup &
	rm bachelor.pdf
